[package]
name = "cherubsh-builtins"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
cherubsh-common = { path = "../common" }
cherubsh-parser = { path = "../parser" }
cherubsh-lexer = { path = "../lexer" }
cherubsh-expander = { path = "../expander" }
libc = "0.2"
bitflags = "2"
