[package]
name = "cherubsh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cherubsh-common = { path = "../common" }
cherubsh-lexer = { path = "../lexer" }
cherubsh-parser = { path = "../parser" }
cherubsh-expander = { path = "../expander" }
cherubsh-exec = { path = "../exec" }
cherubsh-builtins = { path = "../builtins" }
cherubsh-lineedit = { path = "../lineedit" }
libc = "0.2"

[dev-dependencies]
cherubsh-test-harness = { path = "../test-harness" }
