/// Saved value of one variable for restoration when a local scope is popped.
#[derive(Debug, Clone)]
pub struct SavedVar {
    pub entry: Option<VariableEntry>,
    pub indexed: Option<IndexedArray>,
    pub assoc: Option<HashMap<String, String>>,
    pub nameref: Option<String>,
}

#[derive(Debug, Clone)]
pub struct SavedOptions {
    pub allexport: bool,
    pub errexit: bool,
    pub nounset: bool,
    pub noglob: bool,
    pub hashall: bool,
    pub keyword: bool,
    pub pipefail: bool,
    pub lastpipe: bool,
    pub noclobber: bool,
    pub xtrace: bool,
    pub braceexpand: bool,
    pub errtrace: bool,
    pub functrace: bool,
    pub physical: bool,
    pub notify: bool,
    pub monitor: bool,
    pub job_control: bool,
    pub noexec: bool,
    pub just_one_command: bool,
    pub privileged_mode: bool,
    pub verbose_flag: bool,
    pub restricted: bool,
    pub posixly_correct: bool,
    pub shopt_options: BTreeMap<String, bool>,
}

pub struct ShellState {
    pub interactive: bool,
    pub interactive_shell: bool,
    pub login_shell: i32,
    pub posixly_correct: bool,
    pub act_like_sh: bool,
    pub su_shell: bool,
    pub forced_interactive: bool,
    pub read_from_stdin: bool,
    pub want_pending_command: bool,
    pub just_one_command: bool,
    pub no_rc: bool,
    pub no_profile: bool,
    pub no_line_editing: bool,
    pub want_initial_help: bool,
    pub do_version: bool,
    pub make_login_shell: bool,
    pub privileged_mode: bool,
    pub restricted: bool,
    pub debugging: bool,
    pub debugger_mode: bool,
    pub noexec: bool,
    pub wordexp_only: bool,
    pub pretty_print_mode: bool,
    pub dump_translatable_strings: bool,
    pub dump_po_strings: bool,
    pub verbose_flag: bool,
    pub command_execution_string: Option<String>,
    pub current_command_string: Option<String>,
    pub shell_script_filename: Option<PathBuf>,
    pub shell_name: String,
    pub shell_invocation_name: String,
    pub rc_file: PathBuf,
    pub dollar_vars: Vec<String>,
    pub last_command_exit_value: i32,
    pub indirection_level: i32,
    pub current_command_number: u64,
    pub executing: bool,
    pub eof_reached: bool,
    pub current_command_line_count: u32,
    mail_last_check: Option<Instant>,
    mail_status: HashMap<PathBuf, MailStatus>,
    pub diagnostic_line_stack: Vec<u32>,
    pub seconds_start: Instant,
    pub shell_start_epoch: i64,
    pub seconds_offset: i64,
    pub seconds_dynamic: bool,
    pub epochseconds_dynamic: bool,
    pub epochrealtime_dynamic: bool,
    pub bash_monoseconds_dynamic: bool,
    pub bash_argv0_dynamic: bool,
    pub groups_dynamic: bool,
    pub random_seed: Cell<u32>,
    pub last_random_value: Cell<i32>,
    pub srandom_seed: Cell<u32>,
    pub startup_state: StartupMode,
    pub running_setuid: bool,
    pub shell_initialized: bool,
    pub input: BashInput,
    pub input_stack: Vec<BashInput>,
    pub input_line_count_stack: Vec<u32>,
    pub variables: HashMap<String, VariableEntry>,
    pub logical_pwd_value: Option<String>,
    pub sourced_env: u32,
    pub allexport: bool,
    pub errexit: bool,
    pub nounset: bool,
    pub noglob: bool,
    pub hashall: bool,
    pub keyword: bool,
    pub pipefail: bool,
    pub lastpipe: bool,
    pub noclobber: bool,
    pub xtrace: bool,
    pub braceexpand: bool,
    pub errtrace: bool,
    pub functrace: bool,
    pub physical: bool,
    pub notify: bool,
    pub monitor: bool,
    pub subshell_environment: bool,
    pub need_here_doc: bool,
    pub last_async_pid: Option<i32>,
    pub pending_coproc_cleanups: Vec<(String, Option<String>)>,
    pub subshell_level: u32,
    pub command_substitution_depth: u32,
    pub bashpid_cache: Option<i32>,
    pub shell_pid_value: Option<i32>,
    pub funcname_stack: Vec<String>,
    pub funcname_source_stack: Vec<String>,
    pub funcname_lineno_stack: Vec<u32>,
    pub funcname_source_frame_stack: Vec<bool>,
    pub bash_argc_stack: Vec<usize>,
    pub bash_argv_stack: Vec<String>,
    pub indexed_arrays: HashMap<String, IndexedArray>,
    pub assoc_arrays: HashMap<String, HashMap<String, String>>,
    pub assoc_print_orders: HashMap<String, Vec<String>>,
    pub preserve_assoc_order_once: HashSet<String>,
    pub nameref_targets: HashMap<String, String>,
    pub local_scopes: Vec<HashMap<String, SavedVar>>,
    pub local_option_scopes: Vec<Option<SavedOptions>>,
    pub aliases: BTreeMap<String, String>,
    pub aliases_enabled: bool,
    pub traps: BTreeMap<String, String>,
    pub trap_actions: HashMap<TrapKind, TrapAction>,
    pub inherited_exit_trap_suppressed: bool,
    pub command_hash: BTreeMap<String, PathBuf>,
    pub command_hash_hits: BTreeMap<String, u64>,
    pub dirs_stack: Vec<PathBuf>,
    pub disabled_builtins: BTreeMap<String, bool>,
    pub function_readonly: std::collections::HashSet<String>,
    pub shopt_options: BTreeMap<String, bool>,

    pub jobs: JobTable,
    pub shell_pgrp_value: i32,
    pub original_pgrp_value: i32,
    pub tty_fd_value: Option<i32>,
    pub job_control: bool,
    pub running_trap_sig: Option<i32>,
    pub history_table: HistoryTable,
    pub history_last_line_added: bool,
    pub histfile: Option<PathBuf>,
    pub histfile_explicit: bool,
    pub histsize: usize,
    pub histfilesize: usize,
    pub histcontrol_flags: HistControl,
    pub compspecs: HashMap<String, CompSpec>,
    pub compspec_order: HashMap<String, u64>,
    pub compspec_next_order: u64,
    pub compspec_initialized: bool,
    pub default_compspec: Option<CompSpec>,
    pub initial_compspec: Option<CompSpec>,
    pub empty_compspec: Option<CompSpec>,
    pub active_completion_options: Option<cherubsh_common::completion::CompOpts>,
    pub active_completion_command: Option<String>,
    pub keymaps: HashMap<String, Keymap>,
    pub active_keymap: String,
    pub line_editor: Option<LineEditor>,
}

impl Default for ShellState {
    fn default() -> Self {
        let shell_pid = unsafe { libc::getpid() };
        let shell_pgrp = unsafe { libc::getpgrp() };
        let disabled_builtins = BTreeMap::new();
        Self {
            interactive: false,
            interactive_shell: false,
            login_shell: 0,
            posixly_correct: false,
            act_like_sh: false,
            su_shell: false,
            forced_interactive: false,
            read_from_stdin: false,
            want_pending_command: false,
            just_one_command: false,
            no_rc: false,
            no_profile: false,
            no_line_editing: false,
            want_initial_help: false,
            do_version: false,
            make_login_shell: false,
            privileged_mode: false,
            restricted: false,
            debugging: false,
            debugger_mode: false,
            noexec: false,
            wordexp_only: false,
            pretty_print_mode: false,
            dump_translatable_strings: false,
            dump_po_strings: false,
            verbose_flag: false,
            command_execution_string: None,
            current_command_string: None,
            shell_script_filename: None,
            shell_name: String::from("cherubsh"),
            shell_invocation_name: String::from("cherubsh"),
            rc_file: default_rc_file(),
            dollar_vars: vec![String::from("cherubsh")],
            last_command_exit_value: 0,
            indirection_level: 0,
            current_command_number: 1,
            executing: false,
            eof_reached: false,
            current_command_line_count: 0,
            mail_last_check: None,
            mail_status: HashMap::default(),
            diagnostic_line_stack: Vec::new(),
            seconds_start: Instant::now(),
            shell_start_epoch: current_epoch_seconds() as i64,
            seconds_offset: 0,
            seconds_dynamic: true,
            epochseconds_dynamic: true,
            epochrealtime_dynamic: true,
            bash_monoseconds_dynamic: true,
            bash_argv0_dynamic: true,
            groups_dynamic: false,
            random_seed: Cell::new(1),
            last_random_value: Cell::new(0),
            srandom_seed: Cell::new(initial_srandom_seed(shell_pid)),
            startup_state: StartupMode::Script,
            running_setuid: false,
            shell_initialized: false,
            input: BashInput::None,
            input_stack: Vec::new(),
            input_line_count_stack: Vec::new(),
            variables: HashMap::default(),
            logical_pwd_value: None,
            sourced_env: 0,
            allexport: false,
            errexit: false,
            nounset: false,
            noglob: false,
            hashall: true,
            keyword: false,
            pipefail: false,
            lastpipe: false,
            noclobber: false,
            xtrace: false,
            braceexpand: true,
            errtrace: false,
            functrace: false,
            physical: false,
            notify: false,
            monitor: false,
            subshell_environment: false,
            need_here_doc: false,
            last_async_pid: None,
            pending_coproc_cleanups: Vec::new(),
            subshell_level: 0,
            command_substitution_depth: 0,
            bashpid_cache: None,
            shell_pid_value: Some(shell_pid),
            funcname_stack: Vec::new(),
            funcname_source_stack: Vec::new(),
            funcname_lineno_stack: Vec::new(),
            funcname_source_frame_stack: Vec::new(),
            bash_argc_stack: Vec::new(),
            bash_argv_stack: Vec::new(),
            indexed_arrays: HashMap::default(),
            assoc_arrays: HashMap::default(),
            assoc_print_orders: HashMap::default(),
            preserve_assoc_order_once: HashSet::default(),
            nameref_targets: HashMap::default(),
            local_scopes: Vec::new(),
            local_option_scopes: Vec::new(),
            aliases: BTreeMap::new(),
            aliases_enabled: false,
            traps: BTreeMap::new(),
            trap_actions: HashMap::default(),
            inherited_exit_trap_suppressed: false,
            command_hash: BTreeMap::new(),
            command_hash_hits: BTreeMap::new(),
            dirs_stack: Vec::new(),
            disabled_builtins,
            function_readonly: std::collections::HashSet::new(),
            shopt_options: BTreeMap::new(),
            jobs: JobTable::new(),
            shell_pgrp_value: shell_pgrp,
            original_pgrp_value: shell_pgrp,
            tty_fd_value: None,
            job_control: false,
            running_trap_sig: None,
            history_table: HistoryTable::new(500),
            history_last_line_added: false,
            histfile: None,
            histfile_explicit: false,
            histsize: 500,
            histfilesize: 500,
            histcontrol_flags: HistControl::empty(),
            compspecs: HashMap::default(),
            compspec_order: HashMap::default(),
            compspec_next_order: 0,
            compspec_initialized: false,
            default_compspec: None,
            initial_compspec: None,
            empty_compspec: None,
            active_completion_options: None,
            active_completion_command: None,
            keymaps: HashMap::default(),
            active_keymap: String::from("emacs"),
            line_editor: None,
        }
    }
}

fn default_keymap(name: &str) -> Option<Keymap> {
    let mut keymap = Keymap::new(name);
    match name {
        "emacs" => keymap.install_emacs_defaults(),
        "vi-insert" => keymap.install_vi_insert_defaults(),
        "vi-command" => keymap.install_vi_movement_defaults(),
        _ => return None,
    }
    Some(keymap)
}
